export const CAMPSITES = [
  {
    id: 0,
    name: "Farm City",
    author: "Novella Carpenter",
    image: "/img/farmcity.jpg",
    featured: true,
    type: "book",
    description:
      "This book is an autobiography by Novella of her journey as she moved to San Fransisco and started an urban farm. It will give you confidence if you want to start an urban garden, with her can-do attitude, she says, 'If I can do it, you can do it too!' without explicitly talking to the reader. Even if you don't want to start your own urban farm, it is a fantastic and invigorating read. ",
  },
  {
    id: 1,
    name: "The Essential Urban Farmer",
    author: ["Novella Carpenter", "Willow Rosenthal"],
    image: "/img/essentialurbanfarmer.jpg",
    featured: false,
    type: "book",
    description: "",
  },
  {
    id: 2,
    name: "Gaia's Garden",
    author: "Toby Hemenway",
    image: "/img/gaiagarden.jpg",
    featured: false,
    type: "book",
    description: "",
  },
  {
    id: 3,
    name: "Chef's Knife",
    author: "Kan",
    image: "/img/kenjilopezaltknife.jpg",
    featured: false,
    type: "tool",
    description: "",
  },
  {
    id: 4,
    name: "Mocajete",
    author: "",
    image: "/img/mocajete.jpg",
    featured: false,
    type: "tool",
    description: "",
  },
];
